source 'https://rubygems.org'

# include the basic plezi framework and server
gem 'plezi', '~> 0.16.0'

## Redis servers are used to allow websocket scaling.
## Plezi can be configured to automatically use Redis for easy scaling.
# gem 'redis'


ruby '2.5.1'
